[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
num-bigint = { version = "0.4", features = [ "rand" ] }
num-traits = "0.2"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
structopt = "0.3"
base64-url = "1.4"
